# Generated by Django 5.2.5 on 2025-08-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('organisme', models.CharField(help_text="Nom de l'organisme", max_length=100)),
                ('image', models.ImageField(upload_to='certicicats/images/')),
                ('fichier_pdf', models.FileField(upload_to='certificats/pdf')),
            ],
        ),
        migrations.CreateModel(
            name='Competences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('icone', models.URLField(help_text='Liens vers icone de la compétence', max_length=255)),
            ],
            options={
                'verbose_name': 'Compétence',
            },
        ),
    ]
