# Generated by Django 5.2.5 on 2025-08-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_carousel', models.ImageField(upload_to='projets/carousels/')),
                ('lien_github', models.URLField()),
                ('est_principal', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Projet',
            },
        ),
    ]
